export const windRadar = 'nsm23' //风廓线雷达
export const airDetect = 'nsm121' //探空云分析
export const localCloud = 'nsm13' //本地云模式
export const shortForecast = 'nsm8'  //短期预报
export const micradiation = 'nsm53'  //微波辐射计
export const actualproduct = 'nsm22'  //实况产品
export const ecwmfInter = 'nsm9'  //ECWMF细网格模式产品 
export const sunflower = 'nsm19'  //葵花8红外灰度图 
export const windradar = 'nsm23' //风廓线雷达
// export const reservoirLevel = '2' //水库水位
export const satelliteProduct = 'nsm20'  //卫星云反演产品
export const grapesMode = 'nsm10' //grapes中尺度模式产品
export const reservoirLevel = '3-ntm2' //水库水位
export const cityShortForecast = 'nsm12'
export const riverLevel = '3-ntm3' //河流水位
export const cityFire = '3-ntm12' //城市火险
export const forestFire = '3-ntm11' //森林火险
export const dryCondition = '3-ntm1' // 干旱
export const grapes1km = 'nsm18'
export const grapes3km = 'nsm17'
export const mountainFlood = "3-ntm9"
export const environmentPublic = "3-ntm15" //环境公报
export const environmentForecast = "3-ntm17" //环境气象预报
export const HumanComfort = "3-ntm14" //人体舒适度
export const SunstrokeIndex = "3-ntm13" //中暑指数
export const weatherForecast = '3-ntm6' //气候预测
export const agricultureAnalysis = '3-ntm4' //农情分析
export const satelliteCloud = 'nsm60'  //卫星云图产品
export const personalManagement = 'nsm48' //人员管理
export const shortRadar = 'nsm21'  //短临产品和雷达综合分析
export const midLongForecast = '3-ntm5' //中长期预报
export const typh = 'nsm64'  //台风
export const airplaneCommand = 'nsm29'  //飞机实时轨迹
export const messageDispatch = 'nsm56' //短信调度
export const jobManagement = 'nsm65' //作业点管理 
export const abilityEstimate = 'nsm51'  //能力评估  
export const disasterManage = 'nsm44'  //灾情管理
export const ammunitionInternet = 'nsm47'  //弹药装备物联网

export const operateDemandAnalysis = 'nsm1'
export const operateDemandSurvey = 'nsm2'
export const operatePlan = 'nsm11'
export const operatePotential = 'nsm14'
export const operateWarningGroundReport = 'nsm24'
export const operateWarningAirReport = 'nsm26'
export const operateGroundPlan = 'nsm25'
export const operateAirPlan = 'nsm27'
export const operateEffectEvaluating = 'nsm35'